version: '3.8'
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=default_password
      - MYSQL_DATABASE=checkpoint
    volumes:
      - mysql:/var/lib/mysql
  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: /data/postgres
      POSTGRES_DB: checkpoint
    volumes:
      - dbdata:/data/postgres
    ports:
      - '5432:5432'
volumes:
  mysql:
    driver: local
  dbdata:
    driver: local
